ash-linux/STIGbyID/cat2/V38444.sls, ash-linux/STIGbyID/cat2/V38512.sls, ash-linux/STIGbyID/cat2/V38513.sls, ash-linux/STIGbyID/cat2/V38555.sls, ash-linux/STIGbyID/cat2/V38560.sls, ash-linux/STIGbyID/cat2/V38686.sls
- Add stig_id var
- Add file var, where appropriate
- Use 'module.function' notation
- Lint (unnecessary spaces ' ')
=> Cleanup iptables states, lint, add stig_id

ash-linux/STIGbyID/cat2/V38512.sls, ash-linux/STIGbyID/cat2/V38555.sls, ash-linux/STIGbyID/cat2/V38560.sls
=> Use 'iptables.save' to ensure '/etc/sysconfig/iptables' exists

ash-linux/STIGbyID/cat3/V38471.sls
=> Fix bad path to helper script

ash-linux/STIGbyID/cat2/V38679.sls
=> Don't fail the state when warning

ash-linux/STIGbyID/cat2/V51391.sls
=> Don't fail the state because aide is missing

ash-linux/STIGbyID/cat2/files/V38663-helper.sh
=> Don't fail the state when the test fails

ash-linux/authconfig.sls
=> Remove parens around test blocks

ash-linux/STIGbyID/cat2/V38481-fix.sls
=> Use pkg.uptodate instead of pkg.latest

ash-linux/STIGbyID/cat2/V38475.sls, ash-linux/STIGbyID/cat2/files/V38475.sh, ash-linux/STIGbyID/cat3/V38572.sls, ash-linux/STIGbyID/cat3/files/V38572.sh
Updated password rule handler-state to meet updated STIG-requirements.
=> Updated Password Rule-Handlers

ash-linux/STIGbyID/cat3/V38655.sls
=> Nuke Reference to /etc/modprobe.conf

ash-linux/STIGbyID/cat3/V38575.sls
=> Add `rmdir` to Audit Rule-String

ash-linux/STIGbyID/cat3/V38494.sls, ash-linux/STIGbyID/cat3/files/V38494-serial_chattr.sh
=> Add Logic to Make /etc/init/serial.conf Immutable

ash-linux/STIGbyID/cat2/V38514.sls, ash-linux/STIGbyID/cat2/V38515.sls, ash-linux/STIGbyID/cat2/V38517.sls, ash-linux/STIGbyID/cat2/V38682.sls, ash-linux/STIGbyID/cat3/V38516.sls
Fixes #117 
Tested idempotency-fix for:
* `/etc/modprobe.d/rds.conf`
* `/etc/modprobe.d/dccp.conf`
* `/etc/modprobe.d/sctp.conf`
* `/etc/modprobe.d/tipc.conf`
* `/etc/modprobe.d/bluetooth.conf`
=> Updates to modprobe.d Handling

ash-linux/STIGbyID/README_GenStubs-EL7.sh.md
Add screen-caps to script-README
=> Add screen-caps

ash-linux/STIGbyID/cat3/V38692.sls
=> Remove inadvertent `^`, fixes #127

ash-linux/STIGbyID/cat2/V38658.sls
=> Update test so `remember=24` is added properly, fixes #128

ash-linux/STIGbyID/cat2/V38686.sls, ash-linux/STIGbyID/cat2/init.sls
=> Ensure FORWARD table is set to DROP

ash-linux/STIGbyID/cat2/V38513.sls
- Use jinja test to add safety rules to /etc/sysconfig/iptables
_only_ if the file does not exist at the beginning of the state
run.
- Use module.run to ensure that the INPUT table is set to DROP
under all conditions.
Fixes #106
=> Rework logic to fix ordering issues with /etc/sysconfig/iptables

ash-linux/el6/STIGbyID/cat3/V38687.sls
=> Update to reflect change from 'openswan' to 'libreswan' in EL 6.8+

ash-linux/el7/STIGbyID/cat1/RHEL-07-020010.sls, ash-linux/el7/STIGbyID/cat1/RHEL-07-020150.sls, ash-linux/el7/STIGbyID/cat1/RHEL-07-020151.sls, ash-linux/el7/STIGbyID/cat1/RHEL-07-020152.sls, ash-linux/el7/STIGbyID/cat1/RHEL-07-020170.sls, ash-linux/el7/STIGbyID/cat1/RHEL-07-020210.sls, ash-linux/el7/STIGbyID/cat1/files/RHEL-07-020010.sh, ash-linux/el7/STIGbyID/cat1/files/RHEL-07-020150.sh, ash-linux/el7/STIGbyID/cat1/files/RHEL-07-020151.sh, ash-linux/el7/STIGbyID/cat1/files/RHEL-07-020152.sh, ash-linux/el7/STIGbyID/cat1/files/RHEL-07-020170.sh, ash-linux/el7/STIGbyID/cat1/files/RHEL-07-020170_helper.sh, ash-linux/el7/STIGbyID/cat1/files/RHEL-07-020210.sh
Push today's changes from personal repo-branch back to org repo-branch
=> Updates: 2016/08/25

ash-linux/el6/STIGbyID/cat2/V38638.sls
=> Merge fix for Issue 167

ash-linux/el7/STIGbyID/cat2/RHEL-07-020650.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-020660.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-020670.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-020680.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-020700.sls
=> Change Salt tag-ID method to better prevent collisions

ash-linux/el7/STIGbyID/cat2/RHEL-07-010030.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-010070.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-010073.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-010074.sls
Included modifications close #187
=> Fixes for Issue 187

ash-linux/el6/STIGbyID/cat2/V38445.sls, ash-linux/el6/STIGbyID/cat2/V38448.sls
=> Sets replace=False when no source is specified

ash-linux/el7/VendorSTIG/remediate.sls, ash-linux/el7/VendorSTIG/report.sls, pillar.example
=> Supports getting scap content locations from pillar

ash-linux/el6/SCAPonly/low/CCE-26981-1.sls, ash-linux/el6/STIGbyID/cat2/V38500.sls, ash-linux/el6/STIGbyID/cat2/V38619.sls, ash-linux/el6/STIGbyID/cat3/V38681.sls, ash-linux/el6/STIGbyID/cat3/V38685.sls, ash-linux/el6/STIGbyID/cat3/V38690.sls
Stops the formula from iterating over all domain users (when joined to a domain).
=> Removes user.list_user and user.getent from el6 states

_modules/ash_linux.py, _states/ash_linux.py
Updated _modules to enable/disable FIPS for a Linux system following the steps provided in documentation.  Also checks status of FIPs for the system.
Adds a _states to enable/disable FIPS.
=> Changing FIPS Mode

_modules/ash_linux.py
Adding ability to include `boot=` argument to GRUB.
=> Include Boot Arg

ash-linux/el6/STIGbyID/cat2/V38511.sls
* Moving the ipv4 forwarding stuff to a 'last-executed' filename in the
/etc/sysctl.d directory should have been more than enough
* However, it wasn't, so had to add a "make sure these conflicting,
Samsonite-gorilla RPMs aren't present to cause problems" package-
removal operation to ensure The Right Thing(TM) happens with older
AMIs.
=> Had to sledghammer it:

ash-linux/audit_load.sls, ash-linux/el6/SCAPonly/init.sls, ash-linux/el6/STIGbyID/init.sls, ash-linux/el7/VendorSTIG/init.sls, ash-linux/el7/stig.sls
=> Add state to apply audit rules changes without a reboot

ash-linux/el7/STIGbyID/cat2/RHEL-07-040350.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-040610.sls, ash-linux/el7/STIGbyID/cat2/files/RHEL-07-040350.sh, ash-linux/el7/STIGbyID/cat2/files/RHEL-07-040610.sh, ash-linux/el7/STIGbyID/cat2/init.sls, ash-linux/el7/STIGbyID/init.sls
=> Add handler for explicitly setting `IgnoreRhosts`

ash-linux/el7/STIGbyID/cat2/RHEL-07-040400.sls, ash-linux/el7/STIGbyID/cat2/files/RHEL-07-040400.sh, ash-linux/el7/STIGbyID/cat2/init.sls, ash-linux/el7/STIGbyID/init.sls, ash-linux/el7/VendorSTIG/init.sls, ash-linux/el7/stig.sls
=> sshd_config `MACs` and `Ciphers` Tweaks

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/documentation-error.md, .github/ISSUE_TEMPLATE/documentation-request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/bug_fix.md, .github/PULL_REQUEST_TEMPLATE/documentation_fix.md, .github/PULL_REQUEST_TEMPLATE/documentation_new.md, .github/PULL_REQUEST_TEMPLATE/generic.md, .github/PULL_REQUEST_TEMPLATE/new_feature.md, .github/contributing.md, .github/issue_template.md, ash-linux/el7/STIGbyID/cat2/RHEL-07-010040.sls, pillar.example
=> Make /etc/issue settable

ash-linux/el7/STIGbyID/cat2/RHEL-07-020020.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-020100.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-030200.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-030360.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-030510.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-030520.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-030530.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-030540.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-030550.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-030740.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-030770.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-030820.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-030840.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-040110.sls, ash-linux/el7/STIGbyID/cat2/files/RHEL-07-020020.sh, ash-linux/el7/STIGbyID/cat2/files/RHEL-07-020100.sh, ash-linux/el7/STIGbyID/cat2/files/RHEL-07-030200.sh, ash-linux/el7/STIGbyID/cat2/files/RHEL-07-040110.sh, ash-linux/el7/STIGbyID/cat2/init.sls
Gets RHEL scans above 97% when applied.
=> More minor spiffs

ash-linux/el7/STIGbyID/cat2/RHEL-07-040560.sls
=> Make more reliable in face of misconfigured yum repositories

ash-linux/el7/STIGbyID/cat2/RHEL-07-040860.sls
=> Gracefully handle lack of an /etc/sysctl.conf file

ash-linux/el7/STIGbyID/cat2/RHEL-07-040160.sls
Closes #304 
Will look for any competing values of:
- `TMOUT=`
- `readonly TMOUT=`
- `declare -r TMOUT=`
Set in _any_ of the `/etc/profile.d` files
=> Ensure no (competing) attempts to set TMOUT

ash-linux/el7/STIGbyID/cat2/RHEL-07-020880.sls
=> Fix 3003's newfound str vs int pickiness in Jinja

_modules/ash_linux.py
If boot mount does not exist (i.e., boot is mounted on `/` instead of `/boot`) then do not add the boot token to the GRUB command line.
=> Check Boot Mount

ash-linux/el8/STIGbyID/cat2/RHEL-08-030740.sls
=> Fix dictionary-key to value actually stored in `os` grain

ash-linux/el7/STIGbyID/cat2/RHEL-07-030819.sls, ash-linux/el7/STIGbyID/cat2/RHEL-07-030840.sls, ash-linux/el7/STIGbyID/cat2/init.sls
Updates audit-method for tracking use of `kmod` program.
Closes #345
=> Remediate SCC finding for V-204563 (RHEL-07-030840)

ash-linux/el7/STIGbyID/cat2/RHEL-07-040830.sls, ash-linux/el7/STIGbyID/cat3/RHEL-07-021270.sls, ash-linux/el7/STIGbyID/cat3/RHEL-07-040530.sls, ash-linux/el7/STIGbyID/cat3/files/RHEL-07-040530.sh, ash-linux/el7/STIGbyID/cat3/init.sls, ash-linux/el7/VendorSTIG/cat3/mount_options_tmp.sls
=> Add handler for vulnerability-ID V-204605

ash-linux/el8/STIGbyID/cat2/RHEL-08-010200.sls, ash-linux/el8/STIGbyID/cat2/files/RHEL-08-010200.sh, ash-linux/el8/STIGbyID/cat2/init.sls
=> Update sshd_config's `ClientAliveCountMax` paramter's value to `1`

ash-linux/el8/STIGbyID/cat2/RHEL-08-020021.sls, ash-linux/el8/STIGbyID/cat2/files/RHEL-08-020021.sh, ash-linux/el8/STIGbyID/cat2/init.sls
=> Ensure that `audit` option is enabled in `/etc/security/faillock.conf`

ash-linux/el8/STIGbyID/cat2/RHEL-08-020231.sls, ash-linux/el8/STIGbyID/cat2/files/RHEL-08-020231.sh, ash-linux/el8/STIGbyID/cat2/init.sls
Sets `PASS_MIN_LEN` value to `15` in the `/etc/login.defs` file
Closes #369
=> Add handlers for V-230370

ash-linux/el8/VendorSTIG/aws_cli_v2.sls
=> Update dependencies to better account for fapolicyd differences between RHEL8 and OL8

ash-linux/el8/STIGbyID/cat3/RHEL-08-030742.sls, ash-linux/el8/STIGbyID/cat3/files/RHEL-08-030742.sh, ash-linux/el8/STIGbyID/cat3/init.sls
=> OS Must disable network management of the chrony daemon

ash-linux/el8/STIGbyID/cat3/RHEL-08-030741.sls, ash-linux/el8/STIGbyID/cat3/files/RHEL-08-030741.sh, ash-linux/el8/STIGbyID/cat3/init.sls
=> Remediates V-230485/RHEL-08-030741 "The OS must disable the chrony daemon from acting as a server."

ash-linux/el8/STIGbyID/cat2/RHEL-08-040290.sls, ash-linux/el8/STIGbyID/cat2/files/RHEL-08-040290.sh, ash-linux/el8/STIGbyID/cat2/init.sls
This MR adds remediation logic to meet the "_OS must be configured to prevent unrestricted mail relaying_" STIG-requirement
Closes #371
=> Remediates V-230550/RHEL-08-040290

README_PillarContents.md
=> Adds elaboration on `pillar.example` file's contents

ash-linux/el7/STIGbyID/cat2/RHEL-07-040320.sls, ash-linux/el7/STIGbyID/cat2/files/RHEL-07-040320.sh, ash-linux/el7/STIGbyID/cat2/init.sls, ash-linux/el7/STIGbyID/cat3/RHEL-07-040600.sls, ash-linux/el7/STIGbyID/cat3/files/RHEL-07-040600.sh, ash-linux/el7/STIGbyID/cat3/init.sls
=> Address V-204587 (RHEL-07-040320)

ash-linux/el8/STIGbyID/cat2/RHEL-08-010358.sls, ash-linux/el8/STIGbyID/cat2/files/RHEL-08-010358.sh
=> Ensure mailx (and related) are available

ash-linux/el8/STIGbyID/cat2/RHEL-08-020025.sls, ash-linux/el8/STIGbyID/cat2/RHEL-08-020026.sls, ash-linux/el8/STIGbyID/cat2/files/RHEL-08-020026.sh, ash-linux/el8/STIGbyID/cat2/init.sls
Ensures requisite `pam_faillock.so` entries in the `/etc/pam.d/password-auth` file
Closes #424
=> Add handler for V-244534 (RHEL-08-020026)

ash-linux/el7/STIGbyID/cat2/RHEL-07-020023.sls, ash-linux/el7/STIGbyID/cat2/files/RHEL-07-020023.sh, ash-linux/el7/STIGbyID/cat2/init.sls
=> Remediate V-250314 (RHEL-07-020023)

ash-linux/el8/STIGbyID/cat2/RHEL-08-030590.sls, ash-linux/el8/STIGbyID/cat2/files/RHEL-08-030590.sh, ash-linux/el8/STIGbyID/cat2/init.sls
=> Log faillock events in audit subsystem

ash-linux/el8/STIGbyID/cat2/RHEL-08-010201.sls, ash-linux/el8/STIGbyID/cat2/files/RHEL-08-010201.sh, ash-linux/el8/STIGbyID/cat2/init.sls
=> Add handler for V-244525 (RHEL-08-010201)

ash-linux/el8/STIGbyID/cat2/RHEL-08-010291.sls, ash-linux/el8/STIGbyID/cat2/files/RHEL-08-010291.sh, ash-linux/el8/STIGbyID/cat2/init.sls
=> Force FIPS-compliant Ciphers in SSH

ash-linux/el8/STIGbyID/cat2/RHEL-08-040342.sls, ash-linux/el8/STIGbyID/cat2/files/RHEL-08-040342.sh, ash-linux/el8/STIGbyID/cat2/init.sls
Adds SSHD kex-config handlers
Closes #466
=> Add Remediation For EL8 STIG Vulnerability-ID V-255924 (RHEL-08-040342)

ash-linux/el9/RuleById/medium/content_rule_postfix_prevent_unrestricted_relay.sls, ash-linux/el9/RuleById/medium/init.sls, pillar.example
=> Adds handler for `content_rule_postfix_prevent_unrestricted_relay` config-setting
