- ash-linux/STIGbyID/cat3/files/V51379-helper.sh
Print a big WARNING, but exit 0.
Fixes #57
> Don't exit with error if selinux disabled

- ash-linux/STIGbyID/cat1/V38666.sls
'pkg.installed' fails if the specified package isn't in the yum
database. this commit checks first whether the package is available,
then installs it if it is. if it isn't available, it prints a warning.
> 'pkg.check_db' checks if hbss pkg is available

- ash-linux/STIGbyID/cat2/files/V38520-helper.sh
Warn if rsyslog hasn't been configured, but exit 0.
Fixes #66
> Don't fail the state from non-actions

- ash-linux/STIGbyID/cat2/V38521.sls
Warn if rsyslog is unconfigured, but exit 0.
Fixes #67
> Don't fail the state due to non-actions

- ash-linux/STIGbyID/cat2/V51875.sls
The 'unless' test executes with any non-zero execute, which includes
when the file doesn't yet exist (even though it will be created by the
state). This cause test=True runs to throw a spurious failure. The
'onlyif' test reverses the logic and so doesn't have the same issue.
Fixes #78
> Use 'onlyif' test to check if pam module in pam file

- ash-linux/scap.sls
- ash-linux/stig.sls
Makes it easier to include a specific baseline.
> Add dedicated 'stig' and 'scap' baseline states

- ash-linux/STIGbyID/cat2/V38481-fix.sls
If there aren't any packages to upgrade, then 'updatePairs' is an empty
dict, which cause a yaml error as the state is incomplete.
Also, instead of looping over the updatePairs dict to create the package
list, just print a list of the keys, using '{{ updatePairs.keys() }}'.
Fixes #81
> Test if there are any packages to upgrade

- ash-linux/SCAPonly/low/CCE-26280-8.sls
- ash-linux/SCAPonly/low/CCE-26731-0.sls
- ash-linux/SCAPonly/low/CCE-26774-0.sls
- ash-linux/SCAPonly/low/CCE-26801-1.sls
- ash-linux/SCAPonly/low/CCE-26883-9.sls
- ash-linux/SCAPonly/low/CCE-26993-6.sls
- ash-linux/SCAPonly/low/CCE-27164-3.sls
- ash-linux/SCAPonly/low/CCE-27196-5.sls
- ash-linux/SCAPonly/low/CCE-27457-1.sls
- ash-linux/SCAPonly/medium/CCE-26741-9.sls
- ash-linux/STIGbyID/cat2/V38444.sls
- ash-linux/STIGbyID/cat2/V38549.sls
- ash-linux/STIGbyID/cat2/V38551.sls
- ash-linux/STIGbyID/cat2/V38553.sls
- ash-linux/STIGbyID/cat3/V38693.sls
Fixes IPv6 state errors when IPv6 is already wholly-disabled (closes #97).
Cleans up miscellaneous issues noted while testing intended fixes (see commit-notes for specifics)
> Add Conditionals to IPv6 states

- ash-linux/STIGbyID/cat3/V38494.sls
The unaltered upstart file, `/etc/init/serial.conf` will undo the changes implemented in the handler for STIG V-38494. This update uses SaltStack's `file.comment` module to defeat this unwanted behavior.
CLoses #101
> Prevent Upstart From Re-populating /etc/securetty

- ash-linux/STIGbyID/cat2/V38513.sls
Use of braces in a `{%- if salt['file.file_exists']` statement causes errors (not previously triggered due to exclusion of state from execution.
`
> Update file-exists if Statement in V38513.sls

- ash-linux/STIGbyID/cat2/init.sls
Uncommented: fix in v2014.7.5, (saltstack/salt#21133) tested good on 2016-01-11
> Update cat2 init.sls

- ash-linux/STIGbyID/cat3/V38554.sls
Per Issue #109, lost b64 rules in favor of b32. This PR adds b64 back so that both b32 and b64 are accounted for on `file.append` operation.
Tested against `file.append` and "already exists" use-case. Does not fix `file.replace` use-case. Will open separate issue to address.
> `fchownat` needs b64 *and b32

- ash-linux/STIGbyID/cat2/V38514.sls
- ash-linux/STIGbyID/cat2/V38515.sls
- ash-linux/STIGbyID/cat2/V38517.sls
- ash-linux/STIGbyID/cat3/V38516.sls
> Update modprobe.d Rules to Used /bin/true Per Updated  STIG Guidance

- ash-linux/STIGbyID/cat2/V38678.sls
Provides graceful fail-back for - what arguably should never happen (only ever encountered in SLIM6 build) - case where `/var/log/audit` directory does not exist.
Fixes #83
> Expand Usability

- ash-linux/STIGbyID/cat2/V38574.sls
grep does not appear to treat `\s` as a shorthand character to
match any whitespace.
The prior test was failing to match conditions that it should have
matched, and the failure was resulting in multiple `sha512` tokens
being placed into `/etc/pam.d/system-auth-ac` on the initial run
of the formula.
Fixes #134
> Do not use \s or [\s] with grep

- ash-linux/el7/STIGbyID/cat3/RHEL-07-040370.sls
**Note:** as of today's commit-date, the `persist` (and `runtime`) option is only available in the development branches of SaltStack. Hopefully, by the time the EL7 STIGs exit beta, these features will have been pushed into SaltStack's main code-branch.
> Fixes #141

- ash-linux/el6/STIGbyID/cat2/V38513.sls
Previously, V38513.sls used a jinja test to check for the existence
of `/etc/sysconfig/iptables`, and only created the safety rules for
iptables if the file was missing. However, the `INPUT` table was
_always_ being configured to `DROP`. For systems where this file
already existed, this combination caused the system to become
unreachable because the safety rules were not being added.
This patch updates V38513.sls to use the newer functions and
parameters available in the `iptables` state module to create a new
chain, `ASH`, jump from the `INPUT` chain to the `ASH` chain, and
creates the safety rules in the `ASH` chain.
Creating the saftey rules is conditional on whether the jump rule
is added to the `INPUT` chain. This means users can modify the
`ASH` chain after the fact if they wish to …
> V38513: Manage iptables safety rules in ASH chain

- ash-linux/el6/STIGbyID/cat2/V38512.sls
Salt 2016.11 runs `iptables-save` when calling `iptables.save`, and
then writes the output to `/etc/sysconfig/iptables`. However, in
some cases, `iptables-save` appears to generate no output. First
running `iptables --list` causes `iptables-save` to output the
expected rules in all (known) cases.
> Lists iptables before saving rules

- ash-linux/el7/VendorSTIG/cat3/files/mount_option_tmp_nodev.sh
- ash-linux/el7/VendorSTIG/cat3/files/mount_option_tmp_noexec.sh
- ash-linux/el7/VendorSTIG/cat3/files/mount_option_tmp_nosuid.sh
- ash-linux/el7/VendorSTIG/cat3/init.sls
- ash-linux/el7/VendorSTIG/cat3/mount_option_tmp_nodev.sls
- ash-linux/el7/VendorSTIG/cat3/mount_option_tmp_noexec.sls
- ash-linux/el7/VendorSTIG/cat3/mount_option_tmp_nosuid.sls
- ash-linux/el7/VendorSTIG/init.sls
- ash-linux/el7/VendorSTIG/packages.sls
- ash-linux/el7/VendorSTIG/remediate.sls
- ash-linux/el7/VendorSTIG/report.sls
Vendor auto-remediation doesn't know how to remediate when /tmp is systemd-managed (as required for tmpfs-based /tmp under EL7)
> Handlers for /tmp mount options

- .travis.yml
- ash-linux/el6/SCAPonly/low/CCE-27011-6.sls
- ash-linux/el6/VendorSTIG/init.sls
- ash-linux/el6/init.sls
- ash-linux/el7/Nessus/init.sls
- ash-linux/el7/SCAPonly/init.sls
- ash-linux/el7/STIGbyID/init.sls
- ash-linux/el7/init.sls
- ash-linux/el7/stig.sls
- ash-linux/init.sls
- ash-linux/vendor.sls
* Uses placeholder/notification states where the baseline for either
el6 or el7 do not currently contain any actions.
* Adds tests for all baseline states.
* Creates a top-level `vendor` baseline for the VendorSTIG (EL7 only).
> Provides same baseline states for both el6 and el7

- ash-linux/el6/STIGbyID/cat2/V38449.sls
- ash-linux/el6/STIGbyID/cat2/V38450.sls
- ash-linux/el6/STIGbyID/cat2/V38451.sls
- ash-linux/el6/STIGbyID/cat2/V38457.sls
- ash-linux/el6/STIGbyID/cat2/V38458.sls
- ash-linux/el6/STIGbyID/cat2/V38459.sls
- ash-linux/el6/STIGbyID/cat2/V38461.sls
- ash-linux/el6/STIGbyID/cat2/V38502.sls
- ash-linux/el6/STIGbyID/cat2/V38503.sls
- ash-linux/el6/STIGbyID/cat2/V38504.sls
- ash-linux/el6/STIGbyID/cat2/V38524.sls
- ash-linux/el6/STIGbyID/cat2/V38526.sls
- ash-linux/el6/STIGbyID/cat2/V38532.sls
- ash-linux/el6/STIGbyID/cat2/V38542.sls
- ash-linux/el6/STIGbyID/cat2/V38579.sls
- ash-linux/el6/STIGbyID/cat2/V38581.sls
- ash-linux/el6/STIGbyID/cat2/V38583.sls
- ash-linux/el6/STIGbyID/cat2/V38600.sls
- ash-linux/el6/STIGbyID/cat3/V38535.sls
- ash-linux/el6/STIGbyID/cat3/V38537.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-020840.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-020850.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040060.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040070.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040080.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040640.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040650.sls
Avoids spurious warning messages of the form:
```
[WARNING ] State for file: <file> - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.
```
> Sets replace=False when not using a source file

- .travis.yml
- _modules/ash_linux.py
- ash-linux/el6/STIGbyID/cat1/V38491.sls
- ash-linux/el6/STIGbyID/cat2/V38496.sls
`user.list_users` will return every ldap-/pam-sourced user, which is the expected behavior of the underlying `pwd` library, but it was not the original intention of these states.
This patch uses the `spwd` library to get a list of shadow users, which better scopes the returned value.
> Adds a custom module to list shadow users and uses that rather than `user.list_users`

- _modules/ash_linux.py
- _states/ash_linux.py
* When executing the `fips_state` state, informs the user of the valid values if `value` is invalid
* Adds a comment to the fips execution module if the FIPS mode is already in the requested state
> Improves messaging in FIPS modules

- ash-linux/el7/Miscellaneous/firewalld_safeties.sls
This method:
* Creates a file that would normally be created via the `firewalld-offline-cmd` command-line utility
* Issues a firewalld service-restart if the target file is new or updated
Was going to code up other methods, but this is both Salt-ier and less prone to shortcomings in Saltstack's current implementation of firewalld.
Note: this module isn't currently linked into any of the `init.sls`, `top.sls` or equivalent activation method.
> Safety implemented via Salt's file.managed method

- ash-linux/el7/STIGbyID/cat2/RHEL-07-040110.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040170.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040191.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040301.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040332.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040334.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040620.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040670.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040690.sls
Prior pattern was inserting the text even when the option was
present (without a space).
This affects many of the el7 STIG states currently. This patch
only corrects the behavior for /etc/ssh/sshd_config.
> Does not _require_ a space in the match pattern

- ash-linux/el7/Miscellaneous/files/firewalld_safeties.sh
This should solve the issue where running the state that changes the default firewalld zone causes future SSH connections to fail.
> Get rid of redundant token (Closes #244)

- ash-linux/el7/STIGbyID/cat1/RHEL-07-010482.sls
- ash-linux/el7/STIGbyID/cat1/files/RHEL-07-010482.sh
- ash-linux/el7/STIGbyID/cat1/init.sls
- ash-linux/el7/STIGbyID/init.sls
- pillar.example
Closes #260 
Use logic to _always_ create/overwrite the `/boot/grub2/user.cfg` file if Pillar value is set while only creating if Pillar value is undef/null _and_ `/boot/grub2/user.cfg` file doesn't already exist
> Add logic to set GRUB2 password

- ash-linux/el7/Miscellaneous/CIS-5_2_3.sls
- ash-linux/el7/Miscellaneous/files/CIS-5_2_3.sh
- ash-linux/el7/VendorSTIG/init.sls
- ash-linux/el7/stig.sls
- pillar.example
Probably need to open a BugZilla to get this removed from the C2S profile. At any rate, closes #253
> Add handlers for CIS 5.2.3 that some scanners/profiles check for

- ash-linux/el7/STIGbyID/cat1/RHEL-07-010482.sls
- pillar.example
Closes #265 
Verified: 
- absent Pillar value, default value's get set
- value from Pillar gets set
- file is regenerated upon change of superuser name's value
> Add logic for changing grub-user's name

- ash-linux/el6/SCAPonly/low/CCE-26340-0.sls
- ash-linux/el6/SCAPonly/low/CCE-26361-6.sls
- ash-linux/el6/SCAPonly/low/CCE-26404-4.sls
- ash-linux/el6/SCAPonly/low/CCE-26544-7.sls
- ash-linux/el6/SCAPonly/low/CCE-26670-0.sls
- ash-linux/el6/SCAPonly/low/CCE-26677-5.sls
- ash-linux/el6/SCAPonly/low/CCE-26800-3.sls
- ash-linux/el7/Miscellaneous/CIS-5_2_5.sls
- ash-linux/el7/Miscellaneous/files/CIS-5_2_5.sh
- ash-linux/el7/VendorSTIG/init.sls
- ash-linux/el7/stig.sls
Closes #270 
Note: for whatever reason, the `OS_VERSION=6 SALT_STATE=ash-linux.scap` is refusing to go green for me. It's not relevant to this change, since it's a change wholly within the EL7 tree, but... May require a force-merge if Travis is going to continue to flake out on it, today.
> Ensure a `MaxAuthTries` value is explicitly set 

- ash-linux/el7/STIGbyID/cat2/RHEL-07-021620.sls
- ash-linux/el7/STIGbyID/init.sls
Closes #284 
Note: even applying this fix, OpenSCAP scan with "stig" profile seems to not properly identify that the prescribed fix-text is present in `/etc/aide.conf`. Will need to see if other scanners also have this error (and update "known findings" documentation).
> Enables FIPS in AIDE rules

- ash-linux/el7/STIGbyID/cat2/RHEL-07-040660.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040670.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040680.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040690.sls
- ash-linux/el7/STIGbyID/cat2/RHEL-07-040700.sls
Addresses problems with too-quickly consecutively-restarting `sshd.service` (closes #297 )
> Change service.running file-check directive from 'watch' to 'listen'

- ash-linux/el7/STIGbyID/cat2/RHEL-07-040470.sls
Suppresses emitting of confusing error when no interfaces are found in PROMISCUOUS mode
Closes #313
> Suppress error when IF not in targeted mode

- ash-linux/el7/STIGbyID/cat2/RHEL-07-040810.sls
Only want to remove the `iptables-services` RPM, not the underlying, core-package `iptables` RPM  (which has a LOT of dependencies that  we DON'T want removed)
> Closes #317

- ash-linux/el7/STIGbyID/cat2/RHEL-07-030819.sls
- ash-linux/el7/STIGbyID/cat2/files/RHEL-07-030819.sh
Closes #344 
Borrow logic from 030820 – changing the audit-key name – to create 030819
> The Red Hat Enterprise Linux operating system must audit all uses of the create_module syscall.

- ash-linux/el7/STIGbyID/cat2/RHEL-07-010270.sls
Closes #343 
Method was updated with the v2r1 STIG-release for EL7. Have updated the previous content's handler to use the updated method. When the state runs:
* The line will be added if absent:
```
salt/utils/files.py:385: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
local:
----------
ID: file-add_RHEL-07-010270-/etc/pam.d/system-auth
Function: file.replace
Name: /etc/pam.d/system-auth
Result: True
Comment: Changes were made
Started: 17:25:48.235672
Duration: 3729.584 ms
Changes:
----------
diff:
---
+++
@@ -21,6 +21,7 @@
password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type=
password    sufficient …
```
> Update method to match STIGv2 (and later) requirements

- ash-linux/el7/STIGbyID/cat2/RHEL-07-040110.sls
More-recent STIGs specify a different list-order for the `/etc/ssh/sshd_config` file's `Ciphers` parameter-value. This update ensures compliance-correctness up through STIGv3r6
Closes #350
> Fix Ciphers parameter's list-order

- ash-linux/el8/STIGbyID/cat1/RHEL-08-020331.sls
- ash-linux/el8/STIGbyID/cat1/RHEL-08-020332.sls
- ash-linux/el8/STIGbyID/cat1/files/RHEL-08-020332.sh
- ash-linux/el8/STIGbyID/cat1/init.sls
Closes #355 
Previous content only remediated `/etc/pam.d/system-auth`; this update adds `/etc/pam.d/password-auth`
> Add /etc/pam.d/password-auth to remediation-list

- ash-linux/el8/STIGbyID/cat2/RHEL-08-020019.sls
- ash-linux/el8/STIGbyID/cat2/files/RHEL-08-020019.sh
- ash-linux/el8/STIGbyID/cat2/init.sls
Ensures that the `silent` feature is activated in the `/etc/security/faillock.conf` file.
Closes #364
> Prevents system messages from being presented after third unsuccessful logon attempt occurs

- ash-linux/el8/STIGbyID/cat2/files/RHEL-08-010671.sh
- ash-linux/el8/STIGbyID/cat2/files/RHEL-08-020021.sh
Discovered previously-missed error in two of the `…/STIGbyID/cat2/files` scripts.
> Fix overlooked missing close-quote

- ash-linux/el8/STIGbyID/cat2/RHEL-08-020180.sls
- ash-linux/el8/STIGbyID/cat2/files/RHEL-08-020180.sh
- ash-linux/el8/STIGbyID/cat2/init.sls
Sets minimum password age of "1" for every enumerated user that has either a null or sub-`1` value for field number 4 in /etc/shadow.
Closes #367
> Addresses V-230364: Set each user's minimum password-age policy-value

- ash-linux/el8/STIGbyID/cat2/RHEL-08-040282.sls
- ash-linux/el8/STIGbyID/cat2/files/RHEL-08-040282.sh
- ash-linux/el8/STIGbyID/cat2/init.sls
Searches the `/etc/sysctl.d/`, `/lib/sysctl.d/`, `/run/sysctl.d`, `/usr/lib/sysctl.d' and `/usr/local/lib/sysctl.d` directories for files containing any setting the `kernel.yama.ptrace_scope` tunable and ensures the value is set to `1. Also checks the `/etc/sysctl.conf` and does the same 
Closes #370
> Ensure that OS restricts usage of ptrace to descendant  processes

- ash-linux/el7/VendorSTIG/remediate.sls
- ash-linux/el8/VendorSTIG/remediate.sls
Using PIPESTATUS on el7 resulted in the error:
/bin/bash: line 0: exit: 2[0]: numeric argument required
> Uses el7 and el8 compatible method to redirect oscap output and preserve return code

- ash-linux/el8/STIGbyID/cat2/RHEL-08-020011.sls
Also:
- renames remaining modification-state, removing the `_fromRpm` suffix
- changes requisite method
- updates replacement-regex
- ensures appropriate content is added if there's no match to the regex
Closes #395
> Gets Rid of Redundant `notRpm` State

- ash-linux/el8/STIGbyID/cat2/RHEL-08-020025.sls
- ash-linux/el8/STIGbyID/cat2/files/RHEL-08-020025.sh
- ash-linux/el8/STIGbyID/cat2/init.sls
Ensures STIG-required `pam_faillock.so`  exist and exist in the proper stack-order(s)
Closes #423
> Add handler for V-244533 (RHEL-08-020025)

- ash-linux/el8/STIGbyID/cat2/RHEL-08-040180.sls
- ash-linux/el8/STIGbyID/cat2/files/RHEL-08-040180.sh
- ash-linux/el8/STIGbyID/cat2/init.sls
Add handler to set the `debug-shell.service`  systemd unit to `masked`.
Closes #421
> Add handler for V-230532 (RHEL-08-040180)

- ash-linux/el8/STIGbyID/cat2/RHEL-08-040090.sls
- ash-linux/el8/STIGbyID/cat2/files/RHEL-08-040090.sh
- ash-linux/el8/STIGbyID/cat2/init.sls
- tests/requirements-el7.txt
- tests/requirements.txt
It _appears_ that the OSCAP content already takes care of this, but this will still show up on _some_ hardening-scans. Adding this state to make it easier to point auditors to a block of code that easily tells them, "yes, watchmaker _is_ setting this, appropriately"
Closes #422
> Add remediation for RHEL-08-040090

- ash-linux/el7/STIGbyID/cat2/RHEL-07-020020.sls
- pillar.example
Adds the ability to read SELinux user-mapping associations from Pillar.
Closes #440
> Allow fine-tuning of SELinux user-mappings

- ash-linux/el8/STIGbyID/cat1/RHEL-08-no_pam_nullok.sls
- ash-linux/el8/STIGbyID/cat2/RHEL-08-pam_faillock.sls
- ash-linux/el8/STIGbyID/cat2/RHEL-08-pam_pwhistory.sls
Remove STIG-ID tags from PAM-config tasks to make them more portably-referenceable.
Works in concert with [join-domain-formula PR #199](https://github.com/plus3it/join-domain-formula/pull/199) to resolve CI errors in the [watchmaker](https://github.com/plus3it/watchmaker/) project.
Closes #450
> Remove STIG-ID tags

- ash-linux/el8/STIGbyID/cat2/RHEL-08-020041.sls
While we're here:
* Split out "is `tmux` available else quit" logic so scanners won't incorrectly mark the greater-logic as invalid
* Change to using (STIG-prescribed) `PS1` instead of checking if shell-attribute indicates interactive ...scanners won't incorrectly mark the logic as invalid
* Use the more-compressed (STIG-prescribed) `case` statement ...so scanners won't incorrectly mark them as invalid
* Remove other "human-friendly" formatting decisions ...so scanners won't incorrectly mark them as invalid
Closes #459
> Get rid of `exec` token

- ash-linux/el8/STIGbyID/cat2/RHEL-08-020035.sls
- ash-linux/el8/STIGbyID/cat2/files/RHEL-08-020035.sh
- ash-linux/el8/STIGbyID/cat2/init.sls
> Add handler to set `StopIdleSessionSec` to STIG-Mandated Value

- ash-linux/el8/STIGbyID/cat2/RHEL-08-010571.sls
Fixes problem where execution of the RHEL-08-010571 state renders `/boot` not mountable at boot-time by systemd.
> Replace deprecated Options-token with DirectoryMode configuration-directive

- ash-linux/el8/VendorSTIG/files/fapolicyd_rules-helper.sh
- ash-linux/el8/VendorSTIG/remediate.sls
Running newer versions of `ocap` in remediation-mode will horribly break a system if one doesn't ensure that suitable `fapolicyd` rule-files are present when `oscap` enables "default-deny" mode. This modification necessary to due some questionable logical-assumptions in Red Hat's installation-routines for the `fapolicyd` RPM.
Closes #484
> Ensure default fapolicyd rules are present

- ash-linux/el8/VendorSTIG/init.sls
- ash-linux/el8/VendorSTIG/scap_undos.sls
Hopefully, the rsyslog "fix" logic is the only one we'll need (and, further hopefully, the content-maintainers accept and agree to fix the bug-repor about rsyslog and logcollector) to put here, but we now have a central place for adding such undos as necessary.
Closes #498
Note: if someone intentionally adds a `*.* @@logcollector` line to their host's `/etc/rsyslog.conf` file _before_ this state is run, this update will cause that entry to be commented out. That said, Red Hat generally recommends that remote-logging be set up in suitable `/etc/rsyslog.d/*` files (which this update wouldn't touch).
> Add a 'SCAP undo' state

- ash-linux/el9/RuleById/medium/content_rule_postfix_client_configure_mail_alias.sls
- pillar.example
Updated to allow Watchmaker to configure not just the `root` user's email-destination (alias), but _any_ local account's email-destination. Change made to create a common Pillar-entry for all (local) users' aliases.
Closes #531
> Generalize Existing alias-setting Logic
